### ISSUE TITLE
规范代码结构、代码模块化

### ISSUE THREAD

**Issue by Arondight** [LinuxHub-Group/lmap#10]
有哪个老大哥知道够浪是怎么组织代码目录的，给浪神也整一套

**Comment by catusax** [comment]
1.文件命名采用全小写或者下划线，不应该有字母
2.代码目录一般是pkg里面，而不是lib

更多规范直接看这里: https://github.com/golang-standards/project-layout

**Comment by catusax** [comment]
https://github.com/LinuxHub-Group/lmap/pull/19
