### ISSUE TITLE
添加许可

### ISSUE THREAD

**Issue by Arondight** [LinuxHub-Group/lmap#3]
建议选择 `BSD` 或者 `Public Domain`，许可中注明 `浪神 (from THE GREATE LinuxHub)`

**Comment by QianNangong** [comment]
GREATE -> GREATEST

**Comment by Arondight** [comment]
> 
> 
> GREATE -> GREATEST

不不，虽然事实如此，但是我们不能这么对外宣称，这也是 LinuxHub 的美德啊！

**Comment by QianNangong** [comment]
> > GREATE -> GREATEST
> 
> 不不，虽然事实如此，但是我们不能这么对外宣称，这也是 LinuxHub 的美德啊！

要么`GREAT`要么`GREATEST`，没有`GREATE`的……

**Comment by misaka4e21** [comment]
BSD 授权条款建议注明类型（三条款 BSD 或者与 MIT 授权条款等价的两条款 BSD），另：四条款 BSD 授权与 GPL 不兼容。以及记得把加州大学董事会换掉。

公有领域在部分国家/地区可能遇到问题，可选择 CC0、WTFPL 之类的替代。

**Comment by Arondight** [comment]
@EddaAkikusa 我写错单词了，小春提个 pr 呗

**Comment by Arondight** [comment]
> 
> 
> BSD 授权条款建议注明类型（三条款 BSD 或者与 MIT 授权条款等价的两条款 BSD），另：四条款 BSD 授权与 GPL 不兼容。以及记得把加州大学董事会换掉。
> 
> 公有领域在部分国家/地区可能遇到问题，可选择 CC0、WTFPL 之类的替代。

还是御坂妹妹知识渊博，太强了
